-- Copyright (C) 2026 SAMURAI (xesdoog) & Contributors.
-- This file is part of Samurai's Scripts.
--
-- Permission is hereby granted to copy, modify, and redistribute
-- this code as long as you respect these conditions:
--	* Credit the owner and contributors.
--	* Provide a copy of or a link to the original license (GPL-3.0 or later); see LICENSE.md or <https://www.gnu.org/licenses/>.


-- Samurai's Scripts Ped Scneario List
--
-- Autogenerated on: <17/12/2025 - 10:12:06>
--
-- Author: SAMURAI (xesdoog)
--

return {
	{
		label = "Browse Phone",
		scenario = "WORLD_HUMAN_STAND_MOBILE",
	},
	{
		label = "Clap",
		scenario = "WORLD_HUMAN_CHEERING",
	},
	{
		label = "Construction: Drill",
		scenario = "WORLD_HUMAN_CONST_DRILL",
	},
	{
		label = "Construction: Hammer",
		scenario = "WORLD_HUMAN_HAMMERING",
	},
	{
		label = "Construction: Welding Torch",
		scenario = "WORLD_HUMAN_WELDING",
	},
	{
		label = "Cook On BBQ",
		scenario = "PROP_HUMAN_BBQ",
	},
	{
		label = "Crouch",
		scenario = "WORLD_HUMAN_INSPECT_CROUCH",
	},
	{
		label = "Drink Beer/Coffee",
		scenario = "WORLD_HUMAN_DRINKING",
	},
	{
		label = "Drug Dealer Smoking",
		scenario = "WORLD_HUMAN_DRUG_DEALER",
	},
	{
		label = "Drug Dealer Tough",
		scenario = "WORLD_HUMAN_DRUG_DEALER_HARD",
	},
	{
		label = "Dumpster Dive",
		scenario = "PROP_HUMAN_BUM_BIN",
	},
	{
		label = "Field Planting",
		scenario = "WORLD_HUMAN_GARDENER_PLANT",
	},
	{
		label = "Field Raking",
		scenario = "WORLD_HUMAN_DRUG_FIELD_WORKERS_RAKE",
	},
	{
		label = "Field Weeding",
		scenario = "WORLD_HUMAN_DRUG_FIELD_WORKERS_WEEDING",
	},
	{
		label = "Film Shocking Event",
		scenario = "WORLD_HUMAN_MOBILE_FILM_SHOCKING",
	},
	{
		label = "Flex Muscles",
		scenario = "WORLD_HUMAN_MUSCLE_FLEX",
	},
	{
		label = "Go Fishing",
		scenario = "WORLD_HUMAN_STAND_FISHING",
	},
	{
		label = "Hangout (conversate)",
		scenario = "WORLD_HUMAN_HANG_OUT_STREET",
	},
	{
		label = "Hangout (dance)",
		scenario = "WORLD_HUMAN_STRIP_WATCH_STAND",
	},
	{
		label = "HOBO Begging",
		scenario = "WORLD_HUMAN_BUM_FREEWAY",
	},
	{
		label = "HOBO Leaning",
		scenario = "PROP_HUMAN_BUM_SHOPPING_CART",
	},
	{
		label = "HOBO Sleeping",
		scenario = "WORLD_HUMAN_BUM_SLUMPED",
	},
	{
		label = " HOBO Standing",
		scenario = "WORLD_HUMAN_BUM_STANDING",
	},
	{
		label = "HOBO Washing",
		scenario = "WORLD_HUMAN_BUM_WASH",
	},
	{
		label = "Hold Clipboard",
		scenario = "WORLD_HUMAN_CLIPBOARD",
	},
	{
		label = "Human Statue",
		scenario = "WORLD_HUMAN_HUMAN_STATUE",
	},
	{
		label = "Inspect",
		scenario = "WORLD_HUMAN_INSPECT_STAND",
	},
	{
		label = "Janitor",
		scenario = "WORLD_HUMAN_JANITOR",
	},
	{
		label = "Jog",
		scenario = "WORLD_HUMAN_JOG",
	},
	{
		label = "Lay On Sunlounger",
		scenario = "PROP_HUMAN_SEAT_SUNLOUNGER",
	},
	{
		label = "Leaf Blower",
		scenario = "WORLD_HUMAN_GARDENER_LEAF_BLOWER",
	},
	{
		label = "Lean 01",
		scenario = "WORLD_HUMAN_LEANING",
	},
	{
		label = "Lean 02",
		scenario = "WORLD_HUMAN_LEANING_CASINO_TERRACE",
	},
	{
		label = "Look At Tourist Map",
		scenario = "WORLD_HUMAN_TOURIST_MAP",
	},
	{
		label = "Look Through Binoculars",
		scenario = "WORLD_HUMAN_BINOCULARS",
	},
	{
		label = "Maid",
		scenario = "WORLD_HUMAN_MAID_CLEAN",
	},
	{
		label = "Mechanic",
		scenario = "WORLD_HUMAN_VEHICLE_MECHANIC",
	},
	{
		label = "Paparazzi",
		scenario = "WORLD_HUMAN_PAPARAZZI",
	},
	{
		label = "Park Attendant",
		scenario = "WORLD_HUMAN_CAR_PARK_ATTENDANT",
	},
	{
		label = "Party",
		scenario = "WORLD_HUMAN_PARTYING",
	},
	{
		label = "Pay For Parking",
		scenario = "PROP_HUMAN_PARKING_METER",
	},
	{
		label = "Picnic",
		scenario = "WORLD_HUMAN_PICNIC",
	},
	{
		label = "Player: Golf",
		scenario = "WORLD_HUMAN_GOLF_PLAYER",
	},
	{
		label = "Player: Tennis",
		scenario = "WORLD_HUMAN_TENNIS_PLAYER",
	},
	{
		label = "Police: Idle",
		scenario = "WORLD_HUMAN_COP_IDLES",
	},
	{
		label = "Process Cocaine",
		scenario = "WORLD_HUMAN_DRUG_PROCESSORS_COKE",
	},
	{
		label = "Process Weed",
		scenario = "WORLD_HUMAN_DRUG_PROCESSORS_WEED",
	},
	{
		label = "Prostitute: High-Class",
		scenario = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS",
	},
	{
		label = "Prostitute: Low-Class",
		scenario = "WORLD_HUMAN_PROSTITUTE_LOW_CLASS",
	},
	{
		label = "Security Guard (check)",
		scenario = "WORLD_HUMAN_GUARD_PATROL",
	},
	{
		label = "Security Guard (stand)",
		scenario = "WORLD_HUMAN_GUARD_STAND",
	},
	{
		label = "Security Guard (torch)",
		scenario = "WORLD_HUMAN_SECURITY_SHINE_TORCH",
	},
	{
		label = "Smoke Cigarette",
		scenario = "WORLD_HUMAN_SMOKING",
	},
	{
		label = "Smoke Weed",
		scenario = "WORLD_HUMAN_SMOKING_POT",
	},
	{
		label = "Sit On Armchair",
		scenario = "PROP_HUMAN_SEAT_ARMCHAIR",
	},
	{
		label = "Sit On Barstool",
		scenario = "PROP_HUMAN_SEAT_BAR",
	},
	{
		label = "Sit On Bench",
		scenario = "PROP_HUMAN_SEAT_BENCH",
	},
	{
		label = "Sit On Bench/Drink",
		scenario = "PROP_HUMAN_SEAT_BENCH_DRINK",
	},
	{
		label = "Sit On Bench/Drink Beer",
		scenario = "PROP_HUMAN_SEAT_BENCH_DRINK_BEER",
	},
	{
		label = "Sit On Bench/Eat",
		scenario = "PROP_HUMAN_SEAT_BENCH_FOOD",
	},
	{
		label = "Sit On Chair",
		scenario = "PROP_HUMAN_SEAT_CHAIR",
	},
	{
		label = "Sit On Chair/Drink",
		scenario = "PROP_HUMAN_SEAT_CHAIR_DRINK",
	},
	{
		label = "Sit On Chair/Drink Beer",
		scenario = "PROP_HUMAN_SEAT_CHAIR_DRINK_BEER",
	},
	{
		label = "Sit On Chair/Eat",
		scenario = "PROP_HUMAN_SEAT_CHAIR_FOOD",
	},
	{
		label = "Sit On Chair Upright",
		scenario = "PROP_HUMAN_SEAT_CHAIR_UPRIGHT",
	},
	{
		label = "Sit On Deckchair",
		scenario = "PROP_HUMAN_SEAT_DECKCHAIR",
	},
	{
		label = "Sit On Deckchair/Drink",
		scenario = "PROP_HUMAN_SEAT_DECKCHAIR_DRINK",
	},
	{
		label = "Sit On Ledge",
		scenario = "WORLD_HUMAN_SEAT_LEDGE",
	},
	{
		label = "Sit On Ledge/Eat",
		scenario = "WORLD_HUMAN_SEAT_LEDGE_EATING",
	},
	{
		label = "Sit On Steps",
		scenario = "WORLD_HUMAN_SEAT_STEPS",
	},
	{
		label = "Sit On Wall",
		scenario = "WORLD_HUMAN_SEAT_WALL",
	},
	{
		label = "Sit On Wall/Eat",
		scenario = "WORLD_HUMAN_SEAT_WALL_EATING",
	},
	{
		label = "Stand Impatiently",
		scenario = "WORLD_HUMAN_STAND_IMPATIENT",
	},
	{
		label = "Stand Near Fire",
		scenario = "WORLD_HUMAN_STAND_FIRE",
	},
	{
		label = "Street Musician",
		scenario = "WORLD_HUMAN_MUSICIAN",
	},
	{
		label = "Sunbathe (lay on back)",
		scenario = "WORLD_HUMAN_SUNBATHE_BACK",
	},
	{
		label = "Sunbathe (lay on stomach)",
		scenario = "WORLD_HUMAN_SUNBATHE",
	},
	{
		label = "Take Photo",
		scenario = "WORLD_HUMAN_TOURIST_MOBILE",
	},
	{
		label = "Use ATM",
		scenario = "PROP_HUMAN_ATM",
	},
	{
		label = "Valet",
		scenario = "WORLD_HUMAN_VALET",
	},
	{
		label = "Wait At Bus Stop",
		scenario = "PROP_HUMAN_SEAT_BUS_STOP_WAIT",
	},
	{
		label = "Watch Stripper",
		scenario = "PROP_HUMAN_SEAT_STRIP_WATCH",
	},
	{
		label = "Window Shop",
		scenario = "WORLD_HUMAN_WINDOW_SHOP_BROWSE",
	},
	{
		label = "Workout: Bench Press",
		scenario = "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS",
	},
	{
		label = "Workout: Chin-ups",
		scenario = "PROP_HUMAN_MUSCLE_CHIN_UPS",
	},
	{
		label = "Workout: Freeweights",
		scenario = "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS",
	},
	{
		label = "Workout: Push-ups",
		scenario = "WORLD_HUMAN_PUSH_UPS",
	},
	{
		label = "Workout: Sit-ups",
		scenario = "WORLD_HUMAN_SIT_UPS",
	},
	{
		label = "Workout: Yoga",
		scenario = "WORLD_HUMAN_YOGA",
	},
}
