-- Samurai's Scripts Synchronized Scene List
--
-- Autogenerated on: <17/12/2025 - 10:12:06>
--
-- Author: SAMURAI (xesdoog)
--

return {
	{
		label = "Keypad Hack (Test1)",
		animDict = "anim_heist@hs3f@ig1_hack_keypad@male@",
		params = {
			looped = false,
			holdLastFrame = true
		},
		origin = {
			isPlayer = false,
			model = "ch_prop_fingerprint_scanner_01d",
			pos_offset = {
				x = 0,
				y = 1,
				z = 0.35
			}
		},
		participants = {
			{
				isPlayer = true,
				isPed = true,
				model = nil,
				animName = "action_var_01",
				playbackRate = 1.0,
			},
			{
				isPlayer = false,
				isPed = false,
				model = "ch_prop_ch_phone_ing_01a",
				animName = "action_var_01_prop_phone_ing",
			},
			{
				isPlayer = false,
				isPed = false,
				model = "ch_prop_ch_usb_drive01x",
				animName = "action_var_01_ch_prop_ch_usb_drive01x"
			},
		}
	},
	{
		label = "Ungodly Filth (Test2)",
		animDict = "rcmpaparazzo_2",
		params = {
			looped = true,
			holdLastFrame = false
		},
		origin = {
			isPlayer = true,
			model = nil,
			pos_offset = nil
		},
		participants = {
			{
				isPlayer = true,
				isPed = true,
				model = nil,
				animName = "shag_loop_a",
				playbackRate = 1000.0,
			},
			{
				isPlayer = false,
				isPed = false,
				model = 1846523796,
				animName = "shag_loop_poppy",
				playbackRate = 1000.0,
			},
		}
	}
}
