-- Samurai's Scripts Action Type Definitions
--
-- Autogenerated on: <17/12/2025 - 10:16:52>
--
-- Author: SAMURAI (xesdoog)
--
-- Note: This file does not have to be required. It only needs to be present in your workspace.
--

---@class AnimPTFX
---@field dict string
---@field name string
---@field rot vec3
---@field pos vec3
---@field delay float
---@field scale float

---@class AnimSFX
---@field speechName string
---@field voiceName string
---@field speechParam string
---@field soundDict? string
---@field soundName? string

---@class AnimProps
---@field rot vec3
---@field pos vec3
---@field model hash
---@field parentBone integer
---@field ptfx AnimPTFX
---@field children AnimProps[]

---@class AnimPropPeds
---@field dict string anim dict
---@field name string anim name
---@field type ePedType
---@field model hash
---@field rot vec3
---@field pos vec3
---@field parentBone integer

---@class SceneParticipant
---@field isPlayer boolean
---@field isPed boolean
---@field animName string
---@field model? string | hash
---@field playbackRate? float
---@field handle? handle -- only after they are spawned

-- Anim typedef
---@class AnimData
---@field label string
---@field dict string
---@field name string
---@field category string
---@field playbackRate float
---@field blendInSpeed float
---@field blendOutSpeed float
---@field playTime float
---@field flags eAnimFlags
---@field props? AnimProps[]
---@field ptfx? AnimPTFX
---@field sfx? AnimSFX
---@field propPeds? AnimPropPeds
---@field type? eActionType

-- Scenario typedef
---@class ScenarioData
---@field label string
---@field scenario string
---@field type? eActionType

-- Synchronized scene typedef
---@class SyncedSceneData
---@field label string
---@field animDict string
---@field params { looped: boolean, holdLastFrame: boolean, startPhase?: float, animSpeed?: float }
---@field origin { isPlayer: boolean, model: string, pos_offset?: vec3 }
---@field participants array<SceneParticipant>
---@field pos_offset? vec3
---@field type? eActionType

---@alias ActionData AnimData | ScenarioData | SyncedSceneData?
