local s_basePath = "includes"
local t_packages = {
    "classes.Time",
    "classes.Vector2",
    "classes.Vector3",
    "data.globals",
    "classes.Color",
    "classes.Memory",
    "classes.Game",
    "classes.Self",
    "classes.Vehicle",
    "data.refs",
    "data.actions",
    "data.objects",
    "data.vehicles",
    "data.peds",
    "services.CommandExecutor",
    "services.CompanionManager",
    "services.GridRenderer",
    "services.PreviewService",
    "services.SceneManager",
    "features.EntityForge",
    "features.DriftMinigame",
    "features.FlareCountermeasures",
    "features.Flatbed",
    "features.YimActionsV3",
    "lib.ss_utils",
    "services.Translator",
    "gui.custom_paints_ui",
    "gui.drift_mode_ui",
    "gui.dunk_ui",
    "gui.entity_forge_ui",
    "gui.flatbed_ui",
    "gui.handling_editor_ui",
    "gui.main_ui",
    "gui.self_ui",
    "gui.settings_ui",
    "gui.soundplayer_ui",
    "gui.vehicle_ui",
    "gui.weapon_ui",
    "gui.world_ui",
    "gui.yav3_ui",
    "gui.yrv2_ui",
}

for _, package in pairs(t_packages) do
    require(string.format("%s.%s", s_basePath, package))
end
